services:
  frontend:
    container_name: practical-test-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
